# Generated by Django 5.2.7 on 2025-11-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_machine_code_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='code',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='is_active',
        ),
        migrations.AddField(
            model_name='plan',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
